### ISSUE TITLE
date-picker 문제해결을 부탁 드립니다.

### ISSUE THREAD

**Issue by kimwonkook** [nhnent/tui.date-picker#13]
<div class="tui-datepicker-input tui-datetime-input tui-has-focus">
            <input type="text" id="datepicker-input-str" aria-label="Date-Time">
            <span class="tui-ico-date"></span>
</div>
<div id="wrapperStr" style="margin-top: -1px;"></div>
<div id="grid"></div>

date-picker를 조회조건으로 상단에 배치후 grid를 밑에 놓고 화면을 구성하였습니다. 근대 date-picker input창을 클릭을 하니깐 date-picker 달력이 그리그 밑으로 사라지는 현상이 발견되었습니다. 아무리 z-index를 줘도 나오지 않습니다. 다른CSS문제인줄알고 다른걸 다 제거후 실행하였지만 증상이 해결이 안되어서 글을 올립니다. grid와 date-picker둘다 toastui를 이용하여서 만든것입니다. 해결방법이 있으면 알려주시기 바랍니다.

**Comment by jinwoo-kim-nhn** [comment]
@kimwonkook  문의주셔서 감사합니다. 아래와 같이 css 에서 tui-datepicker 의 z-index를 주시면 됩니다.
~~~
.tui-datepicker {
    z-index: 1;
}
~~~
